version: '3.4'

services:
  back:
    image: back
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    env_file:
      - ".env"
    ports:
      - 3001:3001
