version: '3.4'

services:
  back:
    image: back
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    env_file:
      - stack.env
    ports:
      - "127.0.0.1:9000:3001"
